### PR TITLE
Update pos_map.py

### PR DESCRIPTION
**Pull request by KoichiYasuoka**
Some quick hacks for issue #82

### CODE REVIEW

**Comment by tsroten** [comment]
@KoichiYasuoka Thanks for the pull request! I like the `raw` idea 👍 

It looks like there are two tests that are failing. Would you be able to update these?

In the file[ `tests/test_pos_map.py`, on line 78](https://github.com/tsroten/pynlpir/blob/develop/tests/test_pos_map.py#L78), it's expecting `None` to be returned (and that's what we want to test for). So, `gms` should likely be changed to another value that does not exist in the POS mapping.

Also, in [`tests/test_init.py`, line 124](https://github.com/tsroten/pynlpir/blob/develop/tests/test_init.py#L124), `甲` should be updated from `numeral` to `numeral:zodiac`.

**Comment by KoichiYasuoka** [comment]
I've rewritten `test_init.py` and `test_pos.map.py` as indicated, but "**All checks have failed**". Umm...

**Comment by tsroten** [comment]
@KoichiYasuoka The related tests are passing again 👍  It appears the other errors in the tests are unrelated (one is a broken URL in the documentation). I'll fix those separately.

Thanks again for your contribution! Do you mind if I add your name to the contributors list with a link to your GitHub profile?

**Comment by KoichiYasuoka** [comment]
Thank you @tsroten for merging, and I'm looking forward to see my name on the contributors. Also I'm looking forward to the update of [pip installer](https://pypi.org/project/PyNLPIR/).

**Comment by tsroten** [comment]
@KoichiYasuoka Thanks again! The new version was [released to PyPI](https://pypi.org/project/PyNLPIR/) today. Also, I've added your name to [the AUTHORS file](https://pynlpir.readthedocs.io/en/latest/authors.html#contributors).

**Pull request merged**
